version: 2

sources:
  - name: erp_adventureworks
    description: Adventure works sales data system 
    database: FEA24_9 
    schema: RAW_ADVENTURE_WORKS 
    tables:
      - name: ADDRESS
        description: "People address table from Adventure Works."
        columns:
        - name: addressid
          description: "Primary key for Address"
          data_tests: 
            - unique
            - not_null
        - name: stateprovinceid
          description: >
            "Unique identification number for the state or province. Foreign key to StateProvince table."
        - name: addressline
          description: "First street address line."
        - name: city
          description: "Name of the city."
        - name: modifieddate
          description: "Date and time the record was last updated."

      - name: PERSON
        description: " All the people involved with AdventureWorks."
        columns:
          - name: businessentityid
            description: "Primary key for Person records."
            data_tests: 
              - unique
              - not_null
          - name: persontype
            description: >
              "Primary type of person: SC = Store Contact, IN = Individual (retail) customer, 
              SP = Sales person, EM = Employee (non-sales), VC = Vendor contact, GC = General contact"
          - name: firstname
            description: "First name of the person."
          - name: middlename
            description: "Middle name or middle initial of the person."
          - name: lastname
            description: "Last name of the person."
          - name: modifieddate
            description: "Date and time the record was last updated."
      
      
      - name: CUSTOMER
        description: "Brings information about the customers"
        columns:
          - name: customerid
            description: "Primary key."
            data_tests: 
              - unique
              - not_null
          - name: personid
            description: "Foreign key to Person.BusinessEntityID"
          - name: storeid
            description: "Foreign key to Store.BusinessEntityID"
          - name: territoryid
            description: >
              "ID of the territory in which the customer is located. Foreign key to SalesTerritory.SalesTerritoryID."
          - name: modifieddate
            description: "Date and time the record was last updated."
      
      
      
      - name: CREDITCARD
        description: brings the CARDTYPE
        columns:
        - name: creditcardid
          description: "Primary key for CreditCard records."
          data_tests: 
            - unique
            - not_null
        - name: cardtype
          description: "Credit card name."
        - name: modifieddate
          description: "Date and time the record was last updated."
      
      
      - name: SALESTERRITORY
        description: brings the countryid and countrycode.
        columns:
          - name: territoryid
            description: "Primary key."
            data_tests: 
              - unique
              - not_null
          - name: territory
            description: "Sales territory description."
          - name: countryregioncode
            description: "ISO standard country or region code. Foreign key to CountryRegion.CountryRegionCode."
          - name: group
            description: "Geographic area to which the sales territory belong."
          - name: salesytd
            description: "Sales in the territory year to date."
          - name: saleslastyear
            description: "Sales in the territory the previous year."
          - name: costytd
            description: "Business costs in the territory year to date."
          - name: costlastyear
            description: "Business costs in the territory the previous year."
          - name: modifieddate
            description: "Date and time the record was last updated."


      - name: PERSONCREDITCARD
        description: "Cross-reference table mapping people to their credit card information in the CreditCard table."
        columns:
          - name: businessentityid
            description: "Business entity identification number. Foreign key to Person.BusinessEntityID."
            data_tests: 
              - unique
              - not_null
          - name: creditcardid
            description: "Credit card identification number. Foreign key to CreditCard.CreditCardID."
          - name: modifieddate
            description: 	"Date and time the record was last updated."
      
      
      - name: COUNTRYREGION
        description: "Brings the country and region codes."
        columns:
        - name: countryregioncode
          description: "ISO standard code for countries and regions."
          data_tests: 
            - unique
            - not_null
        - name: country_name
          description: "Country or region name."
        - name: modifieddate
          description: "Date and time the record was last updated."
      
      
      - name: STATEPROVINCE
        description: " Brings the State and province."
        columns:
          - name: stateprovinceid
            description: "Primary key for StateProvince records."
            data_tests: 
              - unique
              - not_null
          - name: stateprovincecode
            description: "ISO standard state or province code."
          - name: countryregioncode
            description: >
              "ISO standard country or region code. Foreign key to CountryRegion.CountryRegionCode."
          - name: territoryid
            description: "ID of the territory in which the state or province is located. Foreign key to SalesTerritory.SalesTerritoryID."
          - name: state_name
            description: "State or province description."
          - name: modifieddate
            description: "Date and time the record was last updated."
      
      
      - name: SALESORDERDETAIL
        description: "General sales order information."
        columns:
          - name: salesorderid
            description: "Primary key. Foreign key to SalesOrderHeader.SalesOrderID."
            tests: 
              - not_null
          - name: orderqty
            description: "Quantity ordered per product."
          - name: productid
            description: "Product sold to customer. Foreign key to Product.ProductID."
          - name: unitprice
            description: "Selling price of a single product."
          - name: unitpricediscount
            description: "Discount amount."
          - name: linetotal
            description: "Per product subtotal. Computed as UnitPrice * (1 - UnitPriceDiscount) * OrderQty."
          - name: modifieddate
            description: "Date and time the record was last updated."
     
     
     
     
     
      - name: SALESORDERHEADER
        description: brings the subtotal, rateamount, freight, totaldue and the ship and due dates.
        columns:
          - name: salesorderid
            description: "Primary key."
            tests: 
              - unique
              - not_null
          - name: orderdate
            description: "Dates the sales order was created."
          - name: duedate
            description: "Date the order is due to the customer."
          - name: shipdate
            description: "Date the order was shipped to the customer."
          - name: status
            description: >
              "Order current status. 1 = In process; 2 = Approved; 3 = Backordered; 4 = Rejected; 
              5 = Shipped; 6 = Cancelled"
          - name: onlineorderflag
            description: "0 = Order placed by sales person. 1 = Order placed online by customer."
          - name: customerid
            description: "Customer identification number. Foreign key to Customer.BusinessEntityID."
          - name: salespersonid
            description: "Sales person who created the sales order. Foreign key to SalesPerson.BusinessEntityID."
          - name: territoryid
            description: "Territory in which the sale was made. Foreign key to SalesTerritory.SalesTerritoryID."
          - name: billtoaddressid
            description: "Customer billing address. Foreign key to Address.AddressID."
          - name: shiptoaddressid
            description: "Customer shipping address. Foreign key to Address.AddressID."
          - name: creditcardid
            description: "Credit card identification number. Foreign key to CreditCard.CreditCardID."
          - name: subtotal
            description: >
              "Sales subtotal. Computed as SUM(SalesOrderDetail.LineTotal)for the appropriate SalesOrderID."
          - name: taxamt
            description: "Tax amount."
          - name: freight
            description: "Shipping cost."
          - name: totaldue
            description: "Total due from customer. Computed as Subtotal + TaxAmt + Freight."
          - name: modifieddate
            description: "Date and time the record was last updated."
     
     
     
     
     
     
      - name: SALESREASON
        description: reason for purchase.
        columns:
        - name: salesreasonid
          description: "Primary key for SalesReason records."
          tests: 
            - unique
            - not_null
        - name: reason  
          description: "Sales reason description."
        - name: reasontype
          description: "Category the sales reason belongs to."
        - name: modifieddate
          description: "Date and time the record was last updated."



      - name: PRODUCT
        description: "Products that are sold or used in the manfacturing of sold products."
        columns:
          - name: productid
            description: "Primary key for Product records."
            tests: 
              - unique
              - not_null
          - name: productsubcategoryid
            description: >
              "Product is a member of this product subcategory. 
              Foreign key to ProductSubCategory.ProductSubCategoryID."
          - name: product_name
            description: "Name of the product."
          - name: productnumber
            description: "Unique product identification number."
          - name: color
            description: "Product color."
          - name: size
            description: "Product size."
          - name: productline
            description: "R = Road, M = Mountain, T = Touring, S = Standard"
          - name: style
            description: "W = Womens, M = Mens, U = Universal"
          - name: standardcost
            description: "Standard cost of the product."
          - name: listprice
            description: "Selling price."
          - name: modifieddate
            description: "Date and time the record was last updated."

 
      - name: PRODUCTCATEGORY
        description: "What is the category of the product."
        columns:
          - name: productcategoryid
            description: "Primary key for ProductCategory records."
            tests: 
              - unique
              - not_null
          - name: product_category
            description: "Category description."
          - name: modifieddate
            description: "Date and time the record was last updated."
 
 
      - name: PRODUCTSUBCATEGORY
        description: "What is the subcategory of the product."
        columns:
          - name: productsubcategoryid
            description: "Primary key for ProductSubcategory records."
            tests: 
              - unique
              - not_null
          - name: productcategoryid
            description: >
              "Product category identification number. Foreign key to ProductCategory.ProductCategoryID."
          - name: product_subcategory
            description: "Subcategory description."
          - name: modifieddate
            description: "Date and time the record was last updated."


